version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - APP_ENV=testing
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=testing
      - DB_USERNAME=root
      - DB_PASSWORD=password

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: